# fly.toml app configuration file generated for inputleap-matterbridge on 2024-09-09T10:49:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'inputleap-matterbridge'
primary_region = 'arn'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[restart]]
  policy = 'always'
  retries = 10
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
