[irc.main]
Server="irc.libera.chat:6697"
Nick="InputLeap[Bridge]"
NickServNick="InputLeap[Bridge]"
UseTLS=true
UseSASL=false
SkipTLSVerify=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[matrix.main]
Server="https://matrix.org"
Login="inputleap-bridge-bot"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true

[discord.main]
Server="1276295166617194496"
AutoWebhooks=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PreserveThreading=true

## IRC <-> Matrix
[[gateway]]
name="inputleap-irc-main"
enable=true

[[gateway.inout]]
account="matrix.main"
channel = "!CQazCnuubucmpcPWmF:matrix.org"

[[gateway.inout]]
account="irc.main"
channel="#inputleap"

[[gateway]]
name="inputleap-irc-dev"
enable=true

[[gateway.inout]]
account="matrix.main"
channel = "!WwOdlyMATveZWpLwQR:matrix.org"

[[gateway.inout]]
account="irc.main"
channel="#inputleap-dev"

## end

[[gateway]]
name="inputleap-matrix-dev"
enable=true

[[gateway.inout]]
account="matrix.main"
channel = "!WwOdlyMATveZWpLwQR:matrix.org"

[[gateway.inout]]
account="discord.main"
channel="inputleap-dev"

[[gateway]]
name="inputleap-matrix-main"
enable=true

[[gateway.inout]]
account="matrix.main"
channel = "!CQazCnuubucmpcPWmF:matrix.org"

[[gateway.inout]]
account="discord.main"
channel="inputleap"

