[irc.main]
Server="irc.ipv4.libera.chat:7070"
Nick="InputLeap[Bridge]"
NickServNick="InputLeap[Bridge]"
UseTLS=true
UseSASL=false
SkipTLSVerify=true
Label="irc"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[matrix.main]
Server="https://matrix.org"
Login="inputleap-bridge-bot"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true

[discord.main]
Server="1276295166617194496"
AutoWebhooks=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PreserveThreading=true

## IRC <-> Matrix
[[gateway]]
name="inputleap-irc-matrix-main"
enable=true

[[gateway.inout]]
account="matrix.main"
channel="!CQazCnuubucmpcPWmF:matrix.org"

[[gateway.inout]]
account="irc.main"
channel="#inputleap"

[[gateway]]
name="inputleap-irc-matrix-dev"
enable=true

[[gateway.inout]]
account="matrix.main"
channel="!WwOdlyMATveZWpLwQR:matrix.org"

[[gateway.inout]]
account="irc.main"
channel="#inputleap-dev"

## Discord <-> Matrix
[[gateway]]
name="inputleap-matrix-discord-main"
enable=true

[[gateway.inout]]
account="matrix.main"
channel="!CQazCnuubucmpcPWmF:matrix.org"

[[gateway.inout]]
account="discord.main"
channel="inputleap"

[[gateway]]
name="inputleap-matrix-discord-dev"
enable=true

[[gateway.inout]]
account="matrix.main"
channel="!WwOdlyMATveZWpLwQR:matrix.org"

[[gateway.inout]]
account="discord.main"
channel="inputleap-dev"

